apiVersion: apps/v1
kind : Deployment
metadata:
   name: myjlc-deployment
spec:
   strategy:
     type: RollingUpdate
   selector:
     matchLabels:
        app: myjlc
   replicas: 5
   template:
      metadata:
        name: myjlc-app
        labels: 
          app: myjlc
      spec:
        containers: 
          - name: mycontainer
            image: nginx
            ports:
             - containerPort: 80