apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirst-deployment
spec:
  selector:
    matchLabels:
      app: myjlc-app
  replicas: 3
  template:
    metadata:
      name: myjlc-pod
      labels:
        app: myjlc-app
    spec:
      containers:
        - name: mydep-container
          image: nginx
          ports:
            - containerPort: 9890