apiVersion: v1
kind: Service
metadata:
  name: jlcapp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: myjlc-app
    type: front-end
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000